const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context={window:{},console,Date,state:{evidence:{},memory:{}}};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/../Resources/learning.js','utf8'),context);
const M=context.window.LearningMath,t=1700000000000,D=M.DAY;
let item=M.scheduleMemory(null,true,false,t);assert.equal(item.interval,1);assert.equal(item.streak,1);assert.equal(M.retention(item,t),1);assert.ok(Math.abs(M.retention(item,t+D)-.75)<1e-9);
item=M.scheduleMemory(item,true,false,t+1000);assert.equal(item.interval,1,'same-day practice must not inflate interval');
const morning=new Date(2026,8,23,0,5).getTime();
const today=M.scheduleMemory(null,true,false,morning);
assert.equal(M.scheduleMemory(today,true,false,morning+20*3600000).interval,1,'20 hours on the same local date must not advance the interval');
const late=M.scheduleMemory(null,true,false,new Date(2026,8,23,23,55).getTime());
assert.equal(M.scheduleMemory(late,true,false,new Date(2026,8,24,0,5).getTime()).interval,1,'crossing midnight alone must not advance the interval');
item=M.scheduleMemory(item,true,false,t+2*D);assert.equal(item.interval,3);
item=M.scheduleMemory(item,false,false,t+5*D);assert.equal(item.interval,.25);assert.equal(item.streak,0);
item=M.scheduleMemory(item,true,false,t+5*D+1000);assert.equal(item.streak,1);assert.equal(item.interval,1);
item=M.scheduleMemory(item,true,true,t+6*D);assert.equal(item.passed,false);assert.equal(item.interval,.25);
assert.ok(M.retention(item,t+30*D)<M.retention(item,t+7*D));
assert.equal(M.skillStats({evidence:{},memory:{}},t).every(s=>s.score===null),true);
vm.runInContext("recordLearning('C1',1,true,false,1,1700000000000);recordLearning('C1',1,false,false,0,1700000001000)",context);
let stats=M.skillStats(context.state,t);assert.equal(stats[0].n,1,'repeated submissions count as one observation');assert.equal(stats[0].score,0);
vm.runInContext("recordLearning('C2',1,true,true,1,1700000000000)",context);stats=M.skillStats(context.state,t);assert.equal(stats[0].score,.2,'assisted pass contributes at most .4');
console.log('PASS: scheduling, failure reset, assisted attempts, retention, cold start, repeated attempts');
const board={ids:['one','two']};assert.equal(M.masteryAt(board,t,{masteryEvents:{}}),0,'Unlearned board starts at zero');
const snap={masteryEvents:{one:[{time:t,score:1,stability:1},{time:t+2*D,score:1,stability:3}]}};
assert.equal(M.masteryAt(board,t-1,snap),0);assert.equal(M.masteryAt(board,t,snap),50,'Coverage denominator includes unlearned items');assert.ok(M.masteryAt(board,t+D,snap)<50,'Decays over actual dates');assert.ok(M.masteryAt(board,t+2*D,snap)>M.masteryAt(board,t+2*D-1,snap),'Review creates an upward change');assert.equal(M.masteryAt(board,t+2*D,snap),50);
console.log('PASS: per-board date curves, unlearned zero, decay and real review recovery');
vm.runInContext(fs.readFileSync(__dirname+'/../Resources/complexity.js','utf8'),context);
const estimates=vm.runInContext('complexityEstimate(32)',context);assert.equal(estimates[1].count,5);assert.equal(estimates[3].count,160);assert.equal(estimates[4].count,1024);assert.equal(estimates[5].count,4294967296);
console.log('PASS: interactive growth calculations');
const curriculum=JSON.parse(fs.readFileSync(__dirname+'/../Resources/curriculum.json','utf8'));
context.problems=curriculum.problems;context.tutorials=curriculum.tutorials;context.modules=curriculum.modules;
const bfs=vm.runInContext("lessonForProblem(problems.find(p=>p.id==='C060'))",context);assert.equal(bfs.lesson.id,'L15-3','BFS exercise must recommend BFS lesson');
console.log('PASS: topic-specific tutorial recommendation');
