'use strict';
const {modules,problems,sources}=window.CURRICULUM;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byID=id=>problems.find(p=>p.id===id)??state.remedialExercises?.find(p=>p.id===id);
let state={drafts:{},progress:{},favorites:[],history:[],reviews:{},last:'C001'},page='home',moduleFilter=0,query='',difficulty='',statusFilter='',bankFilter='',current=null,statementTab='problem',consoleTab='checks',busy=false,lastResults={},revealed=new Set(),saveTimer,toastTimer,loaded=false;
const native=!!window.webkit?.messageHandlers?.native;
function post(action,data={}){if(native)window.webkit.messageHandlers.native.postMessage({action,...data});else if(action==='save'){localStorage.setItem('cpractice-preview',JSON.stringify(state));$('#save-status').textContent='浏览器预览 · 已保存';}}
function persist(){if(!loaded)return;clearTimeout(saveTimer);$('#save-status').textContent='保存中…';saveTimer=setTimeout(()=>post('save',{state}),250);}
function flush(){clearTimeout(saveTimer);if(loaded)post('save',{state});}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function foundationCount(mod){return (window.C_FOUNDATIONS?.modules??[]).filter(m=>!mod||m.moduleId===mod).reduce((n,m)=>n+m.points.length,0);}
function completed(id){return !!state.progress[id]?.passed;}
function moduleProgress(id){const ps=problems.filter(p=>p.module===id&&p.bank!=='comprehensive');return [ps.filter(p=>completed(p.id)).length,ps.length];}
function updateSidebar(){
 $('#nav-total').textContent=problems.length;$('#nav-lessons').textContent=tutorials.reduce((n,t)=>n+t.lessons.length,0)+'课 + '+foundationCount()+'点';$('#nav-comprehensive').textContent=problems.filter(p=>p.bank==='comprehensive').length;$('#nav-sports').textContent=problems.filter(p=>p.collection==='sports').length;$('#nav-olympiad').textContent=problems.filter(p=>p.collection==='olympiad').length;
 const count=problems.filter(p=>completed(p.id)).length;$('#side-progress').textContent=`${count} / ${problems.length}`;$('#side-fill').style.width=`${100*count/problems.length}%`;
 $('#chapters').innerHTML=modules.map(m=>{const [n,total]=moduleProgress(m.id);return `<button class="chapter ${(moduleFilter===m.id&&page==='library')||(page==='tutorial'&&tutorialModule===m.id)?'active':''}" data-module="${m.id}"><span class="num">${String(m.id).padStart(2,'0')}</span>${esc(m.title)}<span class="count">${n}/${total}</span></button>`}).join('');
 $$('#chapters button').forEach(b=>b.onclick=()=>openTutorial(+b.dataset.module));
 $$('#primary-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
}
function navigate(target,mod=0){rememberComposer();if(target==='tutorial'){openTutorial(state.lessonLast?.module??1,state.lessonLast?.index??0);return;}saveDraft();page=target;moduleFilter=mod;query='';difficulty='';statusFilter='';bankFilter=['comprehensive','sports','olympiad'].includes(target)?target:mod?'chapter':'';current=null;render();}
function render(){window.CEditor?.dispose();updateSidebar();const name={home:'学习路径',library:moduleFilter?modules[moduleFilter-1].title:'全部题库',favorites:'我的收藏',history:'提交记录',practice:'练习工作台',tutorial:'学习教程',comprehensive:'综合挑战',sports:'足球与篮球',olympiad:'竞赛困难挑战',learning:'能力与复习',mistakes:'错题本',complexity:'复杂度实验室',agent:'C 语言导师',archives:'存档',connection:'连接 Codex',acknowledgements:'来源与致谢'}[page];$('#breadcrumb').innerHTML=`我的工作台 <span>/</span> ${esc(name)}`;
 if(['agent','archives'].includes(page))renderStudy();else if(page==='connection')renderConnection();else if(page==='acknowledgements')renderAcknowledgements();else if(page==='home')renderHome();else if(['library','favorites','comprehensive','sports','olympiad'].includes(page))renderLibrary();else if(page==='complexity')renderComplexity();else if(page==='learning')renderLearning();else if(page==='mistakes')renderMistakes();else if(page==='history')renderHistory();else if(page==='tutorial')renderTutorial();else renderPractice();
}
function highlight(code){
 const re=/(\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|^[ \t]*#[^\n]*|\b(?:int|char|long|short|float|double|void|unsigned|signed|const|static|struct|typedef|enum|return|if|else|for|while|do|break|continue|switch|case|default|sizeof|NULL)\b|\b\d+(?:\.\d+)?(?:[uUlLfF]+)?\b|\b[a-zA-Z_]\w*(?=\s*\())/gm;
 let result='',pos=0;for(const m of code.matchAll(re)){result+=esc(code.slice(pos,m.index));const t=m[0];let c=t.startsWith('//')||t.startsWith('/*')?'comment':t.startsWith('"')||t.startsWith("'")?'str':t.trimStart().startsWith('#')?'preproc':/^\d/.test(t)?'number':/^(int|char|long|short|float|double|void|unsigned|signed|const|static|struct|typedef|enum|return|if|else|for|while|do|break|continue|switch|case|default|sizeof|NULL)$/.test(t)?'kw':'fn';if(c==='kw'&&/^(int|char|long|short|float|double|void|unsigned|signed)$/.test(t))c='type';else if(c==='kw'&&/^(if|else|for|while|return|do|break|continue|switch|case|default)$/.test(t))c='control';const token=c==='str'?esc(t).replace(/%[-+ #0]*\d*(?:\.\d+)?(?:hh|ll|[hlLjzt])?[diuoxXfFeEgGaAcspn%]/g,v=>`<span class="fmt">${v}</span>`):esc(t);result+=`<span class="${c}">${token}</span>`;pos=m.index+t.length;}return result+esc(code.slice(pos));
}
function renderHome(){
 const solved=problems.filter(p=>completed(p.id)).length,attempts=state.history.length;
 const next=byID(state.last)||problems.find(p=>!completed(p.id))||problems[0];
 $('#main').innerHTML=`<div class="page"><div class="eyebrow">LEARN. BUILD. UNDERSTAND.</div><h1 class="page-title">每一行代码，都是进步。</h1><p class="subtitle">从第一个 Hello, C! 到独立解决问题。循序渐进，在实践中真正理解 C。</p>
 <section class="hero"><div class="hero-copy"><div class="hero-label">${state.drafts[next.id]?'继续上次的探索':'你的第一步，从这里开始'} <span class="inline-code"> / CHAPTER ${String(next.module).padStart(2,'0')}</span></div><h2>${esc(next.title)}</h2><p>${esc(modules[next.module-1].subtitle)} · ${next.tests.length} 个验证检查点</p><button class="button primary" id="continue-button">${state.drafts[next.id]?'继续练习':'开始写第一段 C 代码'} <span>↗</span></button></div><div class="hero-code"><div class="filename"><span class="c-icon">C</span> &nbsp; hello.c</div><pre>${highlight('#include <stdio.h>\n\nint main(void) {\n    printf("Hello, C!\\n");\n    return 0;\n}')}</pre><div class="watermark">SMALL STEPS. REAL PROGRESS.</div></div></section>
 <div class="stats"><div class="stat"><div class="stat-icon">▤</div><div><strong>${problems.length}<small>道</small></strong><p>原创分级练习</p></div></div><div class="stat"><div class="stat-icon">⌘</div><div><strong>15<small>章</small></strong><p>${tutorials.reduce((n,t)=>n+t.lessons.length,0)} 节课程 · ${foundationCount()} 个基础点</p></div></div><div class="stat"><div class="stat-icon">✓</div><div><strong class="pass">${solved}<small>/ ${problems.length}</small></strong><p>已通过全部检查点</p></div></div><div class="stat"><div class="stat-icon">◷</div><div><strong>${attempts}<small>次</small></strong><p>本机保存的验证记录</p></div></div></div>
 ${collectionCards()}<div class="section-head"><div><h2>循序渐进的学习路径</h2><p>${tutorials.reduce((n,t)=>n+t.lessons.length,0)} 节课程 + ${foundationCount()} 个基础点细讲：小白形象理解 + 专业准确理解。先学，再练，再验证。</p></div><button class="text-btn" id="all-problems">浏览全部题目 →</button></div><div class="module-grid">${modules.map(m=>{const[n,t]=moduleProgress(m.id);return `<button class="module-card" data-module="${m.id}"><span class="module-no">CHAPTER ${String(m.id).padStart(2,'0')}</span><span class="arrow">↗</span><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p><div class="module-meta"><span>${m.id<=4?'起步 · 建立直觉':m.id<=9?'基础 · 深入语言':m.id<=12?'进阶 · 走近系统':'挑战 · 解决问题'}</span><span>${tutorials[m.id-1].lessons.length} 课 · ${foundationCount(m.id)} 个细讲 · ${n}/${t} 题</span></div><div class="progress-track"><i style="width:${100*n/t}%"></i></div></button>`}).join('')}</div>
 <p class="source-note">原创中文题面与参考解。课程组织参考 ${sources.map((s,i)=>`<button data-source="${i}">${esc(s.title)}</button>`).join(' · ')}。题目与第三方平台无隶属关系。</p></div>`;
 bindCollectionCards();$('#continue-button').onclick=()=>openProblem(next.id);$('#all-problems').onclick=()=>navigate('library');$$('.module-card').forEach(b=>b.onclick=()=>openTutorial(+b.dataset.module));$$('[data-source]').forEach(b=>b.onclick=()=>post('openURL',{url:sources[+b.dataset.source].url}));
}
function filteredProblems(){return (page==='favorites'?[...problems,...(state.remedialExercises??[])]:problems).filter(p=>(!moduleFilter||p.module===moduleFilter)&&(page!=='favorites'||state.favorites.includes(p.id))&&matchesBank(p,bankFilter)&&(!difficulty||p.level===difficulty)&&(!query||`${p.id} ${p.title} ${p.description} ${(p.tags??[]).join(" ")} ${p.topic??""} ${modules[p.module-1].title}`.toLowerCase().includes(query.toLowerCase()))&&(!statusFilter||(statusFilter==='passed'?completed(p.id):!completed(p.id))));}
function renderLibrary(){const m=moduleFilter?modules[moduleFilter-1]:null;
 $('#main').innerHTML=`<div class="page"><div class="eyebrow">${m?'CHAPTER '+String(m.id).padStart(2,'0'):'PRACTICE LIBRARY'}</div><h1 class="page-title">${m?esc(m.title):page==='favorites'?'值得再练一次的题目':page==='sports'?'把球场上的问题，变成算法。':page==='olympiad'?'从部分解，走到完整解。':page==='comprehensive'?'从知识点，走向完整问题。':'把知识，写成代码。'}</h1><p class="subtitle">${m?esc(m.subtitle):page==='sports'?'25道足球 + 25道篮球原创综合题，难度中等偏上。各题使用明确自定义的场景规则。':page==='olympiad'?'100道困难题，覆盖图论、树、数据结构、字符串、数论、动态规划与几何。先审约束、再建模证明，最后优化复杂度。':`${problems.filter(p=>p.bank!=='comprehensive').length} 道分章练习 + ${problems.filter(p=>p.bank==='comprehensive').length} 道综合题。搜索编号、生活场景或算法主题。`}</p>${m?`<div class="lesson-banner">${esc(m.lesson)}<br><button class="text-btn" id="open-lesson" style="padding:8px 0 0;color:var(--green)">学习本章完整教程 ↗</button></div>`:''}<div style="margin-top:15px"><button class="button quiet small" id="open-complexity">复杂度实验室 · 时间 / 空间如何推导 →</button></div><div class="filter-bar"><div class="searchbox"><span>⌕</span><input id="search" placeholder="搜索题目、知识点或编号…" aria-label="搜索题目"></div><select id="bank-filter" aria-label="题库类型"><option value="">全部题库</option><option value="chapter">分章练习</option><option value="comprehensive">全部综合题</option><option value="classic">经典综合200题</option><option value="sports">足球与篮球</option><option value="football">仅足球</option><option value="basketball">仅篮球</option><option value="olympiad">竞赛困难挑战</option></select><select id="difficulty" aria-label="难度筛选"><option value="">全部难度</option>${['入门','基础','进阶','挑战','困难'].map(s=>`<option>${s}</option>`).join('')}</select><select id="status-filter" aria-label="完成状态筛选"><option value="">全部状态</option><option value="todo">未完成</option><option value="passed">已通过</option></select></div><div class="section-head"><p id="result-count"></p><span class="muted" style="font-size:10px">每道题均含提示、参考解与自动验证</span></div><div id="problem-list"></div></div>`;
 $('#open-complexity').onclick=()=>navigate('complexity');$('#bank-filter').value=bankFilter;$('#bank-filter').onchange=e=>{bankFilter=e.target.value;renderProblemList();};$('#search').value=query;$('#search').oninput=e=>{query=e.target.value;renderProblemList();};$('#difficulty').value=difficulty;$('#difficulty').onchange=e=>{difficulty=e.target.value;renderProblemList();};$('#status-filter').value=statusFilter;$('#status-filter').onchange=e=>{statusFilter=e.target.value;renderProblemList();};if(m)$('#open-lesson').onclick=()=>openTutorial(m.id);renderProblemList();
}
function renderProblemList(){const list=filteredProblems();$('#result-count').textContent=`${list.length} 道练习`;
 $('#problem-list').innerHTML=list.length?`<table class="problem-table"><thead><tr><th style="width:35px">状态</th><th>编号</th><th>题目</th><th>难度</th><th>检查点</th><th></th></tr></thead><tbody>${list.map(p=>`<tr class="problem-row" data-id="${p.id}" tabindex="0" role="button" aria-label="练习 ${esc(p.title)}"><td class="${completed(p.id)?'pass':'muted'}">${completed(p.id)?'✓':'○'}</td><td class="id-cell">${p.id}</td><td class="problem-name">${esc(p.title)}<small>${esc(p.topic??modules[p.module-1].title)} · ${collectionLabel(p)}</small></td><td><span class="badge ${p.level}">${p.level}</span></td><td class="muted">${p.tests.length} 项</td><td><button class="star ${state.favorites.includes(p.id)?'on':''}" data-star="${p.id}" aria-label="收藏 ${esc(p.title)}">${state.favorites.includes(p.id)?'★':'☆'}</button></td></tr>`).join('')}</tbody></table>`:`<div class="empty">${page==='favorites'?'还没有收藏的题目。点击题目旁的 ☆，把想复习的内容留在这里。':'没有匹配的题目，试试调整关键词或筛选条件。'}</div>`;
 $$('.problem-row').forEach(r=>{r.onclick=()=>openProblem(r.dataset.id);r.onkeydown=e=>{if(e.key==='Enter')openProblem(r.dataset.id);};});$$('[data-star]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleStar(b.dataset.star);renderProblemList();});
}
function toggleStar(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];persist();}
function saveDraft(){if(current&&$('#code')){state.drafts[current.id]={code:$('#code').value,input:$('#custom-input')?.value??state.drafts[current.id]?.input??current.tests[0].input,name:state.drafts[current.id]?.name??'main.c'};persist();}}
function codeFor(p){return state.drafts[p.id]?.code??p.starter;}
function openProblem(id){saveDraft();current=byID(id);if(!current)return;revealed.delete(id);state.last=id;page='practice';statementTab='problem';consoleTab='checks';persist();render();}
function renderPractice(){if(!current){navigate('home');return;}const p=current;
 $('#main').innerHTML=`<div class="workspace"><div class="work-toolbar"><div class="work-title"><button class="icon-btn" id="back-button" title="${p.collection?'返回专题题库':p.bank==='comprehensive'?'返回综合题库':'返回本章题库'}">‹</button><span class="id-cell">${p.id}</span><h2>${esc(p.title)}</h2><button class="star ${state.favorites.includes(p.id)?'on':''}" id="work-star" title="收藏题目">${state.favorites.includes(p.id)?'★':'☆'}</button></div><div class="work-actions"><button class="button quiet" id="import-button">↥ 导入 .c</button><button class="button" id="analyze-button" title="调用 GPT-5.6-Sol Medium 分析当前代码">详细分析</button><button class="button" id="run-button">▷ 运行</button><button class="button primary" id="judge-button">✓ 检查全部</button><button class="button quiet" id="stop-button" hidden>停止</button></div></div><div class="work-columns"><section class="statement-pane"><div class="tabs" id="statement-tabs">${[['problem','题目描述'],['lesson','学习教程'],['hints','思路提示'],['solution','参考解']].map(([id,label])=>`<button class="tab" data-tab="${id}">${label}</button>`).join('')}</div><div class="statement" id="statement"></div></section><section class="editor-pane"><div class="file-tabs"><div class="file-tab"><span class="c-icon">C</span><span id="file-name">${esc(state.drafts[p.id]?.name??'main.c')}</span><span id="draft-dot" title="自动保存">●</span></div><div class="editor-tools"><button id="vscode-button" title="使用本机 VS Code 扩展与调试器">VS Code ↗</button><button id="reload-vscode">取回代码</button><button id="format-button" title="clang-format 格式化">格式化</button><button id="command-button" title="命令面板">⌘ ⇧ P</button><button id="font-button" title="调整字号">A±</button><button id="find-button">查找 ⌘F</button><button id="reset-button">重置</button><button id="export-button">导出 ↗</button></div></div><div class="editor-path"><span>workspace › ${p.id.toLowerCase()} › main.c</span><span id="pass-state">${completed(p.id)?'✓ 曾通过全部检查':'编写你的解答'}</span></div><div class="editor-shell"><pre class="line-numbers" id="line-numbers" aria-hidden="true"></pre><div class="code-area"><pre id="highlight" aria-hidden="true"></pre><textarea id="code" aria-label="C 语言代码编辑器" spellcheck="false" autocorrect="off" autocapitalize="off" wrap="off"></textarea></div><div class="findbar" id="findbar" hidden><input id="find-input" placeholder="查找代码…" aria-label="查找代码"><button id="find-next" title="下一个">↓</button><button id="find-close" title="关闭查找">×</button></div></div><div class="cursor-status"><span id="cursor-position">Ln 1, Col 1</span><span>Spaces: 4 &nbsp; UTF-8 &nbsp; C17</span></div><section class="console"><div class="tabs" id="console-tabs"><button class="tab" data-console="checks">检查点</button><button class="tab" data-console="input">自定义输入</button><button class="tab" data-console="diagnostics">编译诊断</button><span class="console-label" id="console-label">LOCAL EXECUTION</span></div><div class="console-body" id="console-body"></div></section></section></div></div>`;
 bindAnalysisControls();$('#back-button').onclick=()=>p.generated?navigate('mistakes'):p.collection?navigate(p.collection):p.bank==='comprehensive'?navigate('comprehensive'):navigate('library',p.module);$('#work-star').onclick=()=>{toggleStar(p.id);$('#work-star').classList.toggle('on',state.favorites.includes(p.id));$('#work-star').textContent=state.favorites.includes(p.id)?'★':'☆';};
 $$('#statement-tabs button').forEach(b=>b.onclick=()=>{statementTab=b.dataset.tab;renderStatement();});$$('#console-tabs button').forEach(b=>b.onclick=()=>{saveDraft();consoleTab=b.dataset.console;renderConsole();});
 $('#code').value=codeFor(p);bindEditor();window.CEditor?.mount($('#code'),p.id);syncAnalysisAnnotations();renderStatement();renderConsole();updateBusy();
 $('#import-button').onclick=()=>{saveDraft();flush();post('import');};$('#export-button').onclick=()=>post('export',{code:$('#code').value,name:`${p.id}-${p.title}.c`});$('#run-button').onclick=()=>startRun('run');$('#judge-button').onclick=()=>startRun('judge');$('#stop-button').onclick=()=>{post('stop');toast('正在停止运行…');};
 $('#vscode-button').onclick=()=>{saveDraft();post('openVSCode',{problemID:p.id,code:codeFor(p)});};$('#reload-vscode').onclick=()=>post('reloadVSCode',{problemID:p.id});$('#format-button').onclick=()=>window.CEditor?.format();$('#command-button').onclick=()=>window.CEditor?.command();$('#find-button').onclick=()=>showFind();$('#find-close').onclick=()=>{$('#findbar').hidden=true;$('#code').focus();};$('#find-next').onclick=()=>findNext();$('#find-input').onkeydown=e=>{if(e.key==='Enter')findNext();if(e.key==='Escape')$('#find-close').click();};
 $('#reset-button').onclick=()=>showModal('重置当前代码',`<p>这会用本题初始模板替换当前草稿，并开始一次不看参考解的独立练习。已保存的提交记录仍可查看和恢复。</p><button class="button" id="confirm-reset">重置为模板</button>`,()=>{$('#confirm-reset').onclick=()=>{$('#code').value=p.starter;revealed.delete(p.id);if(state.assistedProblems)delete state.assistedProblems[p.id];delete lastResults[p.id];statementTab='problem';editorChanged();renderStatement();renderConsole();$('#modal').close();toast('已恢复初始模板');};});
 $('#font-button').onclick=()=>{state.font=state.font===16?12:(state.font??13)+1;applyFont();persist();};applyFont();
}
function renderStatement(){const p=current,m=modules[p.module-1];$$('#statement-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===statementTab));let html='';
 if(statementTab==='problem')html=`<div class="eyebrow">${p.id} / CHAPTER ${String(p.module).padStart(2,'0')}</div><h2>${esc(p.title)}</h2><div class="tags"><span class="badge ${p.level}">${p.level}</span><span class="tag">${esc(m.title)}</span><span class="tag">${collectionLabel(p)}</span><span class="tag">${p.tests.length} 检查点</span></div><p class="fulltext">${esc(p.description)}</p><h3>输入格式</h3><p class="note">本题只有一组数据，不需要先读取测试组数。</p><p class="fulltext">${esc(p.input)}</p><h3>输出格式</h3><p class="fulltext">${esc(p.output)}</p><h3>样例</h3>${(p.displayExamples??[0,1].slice(0,p.tests.length)).map((index,i)=>{const t=p.tests[index];return `<div class="example"><div class="example-title">EXAMPLE ${String(i+1).padStart(2,'0')}</div><div class="example-body"><label>输入</label><pre>${esc(t.input||'（无标准输入）')}</pre>${Object.entries(t.files??{}).map(([name,text])=>`<label>测试文件 · ${esc(name)}</label><pre>${esc(text||'（空文件）')}</pre>`).join('')}<label>输出</label><pre>${esc(t.expected||'（空输出）')}</pre>${p.sampleNotes?.[index]?`<p class="fulltext sample-note">${esc(p.sampleNotes[index])}</p>`:''}</div></div>`;}).join('')}${p.sampleExplanation?`<h3>样例一解释</h3><p class="fulltext">${esc(p.sampleExplanation)}</p>`:''}${p.clarificationExample?`<h3>把规则说清楚 · 补充例子</h3><p class="fulltext">${esc(p.clarificationExample)}</p>`:""}<h3>数据范围</h3><p class="fulltext">${esc(p.constraints)}</p>${subtaskStatement(p)}<p class="note">C17 · 每个检查点最多运行 8 秒。输出按空白分隔比较，忽略多余空格与换行；数值、大小写和标点需符合题意。</p><h3>学习自检</h3><p style="font-size:10px">以下由你确认，不计入自动判题结果。</p>${p.review.map((s,i)=>`<label class="review-item"><input type="checkbox" data-review="${i}" ${state.reviews[p.id]?.includes(i)?'checked':''}>${esc(s)}</label>`).join('')}<button class="button quiet" id="next-problem" style="margin-top:15px">${p.generated?'返回错题本':p===problems.at(-1)?'回到学习路径':'下一道练习 →'}</button>`;
 else if(statementTab==='lesson'){renderEmbeddedTutorial(p.module,$('#statement'));return;}
 else if(statementTab==='hints')html=`<div class="eyebrow">A LITTLE NUDGE</div><h2>先思考，再展开。</h2><p>卡住时，一次只看一个提示。写出伪代码，再把思路翻译成 C。</p>${p.bank==='comprehensive'?'<p class="note">先写清 n、m 分别表示什么；估计朴素方法的循环次数，再寻找可复用的信息。最后清点额外数组、队列与递归栈，分别给出时间与空间复杂度。</p>':''}${p.hints.map((h,i)=>`<details class="hint-card"><summary>提示 ${i+1}${i===p.hints.length-1?' · 完整思路':''}</summary><p>${esc(h)}</p></details>`).join('')}<p class="note">先用最小输入手算，再检查零值、负数和重复元素。编译器警告也值得逐条阅读。</p>`;
 else if(!revealed.has(p.id))html=`<div class="eyebrow">REFERENCE SOLUTION</div><h2>把答案留到最后。</h2><p>参考解包含完整实现。建议先尝试并查看提示，再对照复盘。</p><button class="button" id="reveal-solution">显示参考解</button><p class="note">查看参考解不会自动完成题目；通过状态仅由“检查全部”的实际结果更新。</p>`;
 else html=`<div class="eyebrow">REFERENCE SOLUTION</div><h2>一种可行的实现</h2><p class="fulltext">${esc(p.explanation)}</p>${p.pseudocode?`<h3>先看伪代码</h3><pre class="codeblock pseudocode">${esc(p.pseudocode)}</pre>`:""}<pre class="codeblock">${highlight(p.solution)}</pre>${complexityCard(p)}<button class="button quiet small" id="independent-retry">恢复模板，独立重做</button><p class="note">建议手动理解并重写。自动测试验证输出与指定文件，递归、指针、宏等实现方式请结合源码自检。</p>`;
 if(statementTab==='solution'&&revealed.has(p.id)&&p.assessment)html+=`<details class="source-model-audit"><summary>命题核对 · 模型与约束</summary><div class="markdown">${renderStudyMarkdown(Object.entries(p.assessment).map(([k,v])=>`${({model:'数学模型',ambiguities:'歧义检查',targetAlgorithm:'目标算法',constraintsReason:'约束与复杂度',difficulty:'难度与知识点',targetedMistake:'本次训练目标',readability:'可读性',rigor:'严谨性',completeness:'完整性',contestQuality:'竞赛规范',limitations:'仍需注意'})[k]??k}：${typeof v==='string'?v:JSON.stringify(v)}`).join('\n\n'))}</div></details>`;
 if(statementTab==='hints')html+=`<h3>我的复盘笔记</h3><textarea id="review-notes" class="notes-input" placeholder="我错在哪里？下次如何检查？先写伪代码，再写 C。" aria-label="复盘笔记">${esc(state.notes?.[p.id]??'')}</textarea>`;$('#statement').innerHTML=html;$$('[data-complexity-lab]').forEach(b=>b.onclick=()=>navigate('complexity'));if($('#review-notes'))$('#review-notes').oninput=e=>{state.notes??={};state.notes[p.id]=e.target.value;persist();};if($('#independent-retry'))$('#independent-retry').onclick=()=>$('#reset-button').click();if($('#full-tutorial'))$('#full-tutorial').onclick=()=>openTutorial(p.module);$$('[data-review]').forEach(c=>c.onchange=()=>{let a=state.reviews[p.id]??[];let i=+c.dataset.review;state.reviews[p.id]=c.checked?[...new Set([...a,i])]:a.filter(x=>x!==i);persist();});$$('[data-related]').forEach(b=>b.onclick=()=>openProblem(b.dataset.related));if($('#reveal-solution'))$('#reveal-solution').onclick=()=>{revealed.add(p.id);state.assistedProblems??={};state.assistedProblems[p.id]=true;persist();renderStatement();};if($('#next-problem'))$('#next-problem').onclick=()=>{if(p.generated){navigate('mistakes');return;}const i=problems.indexOf(p);i===problems.length-1?navigate('home'):openProblem(problems[i+1].id);};
}
const statusLabels={passed:'通过',wrong_answer:'答案不符',runtime_error:'运行异常',timeout:'运行超时',ran:'运行完成',compile_error:'编译错误',compile_timeout:'编译超时',error:'无法运行',cancelled:'已停止',failed:'未通过全部检查'};
function renderConsole(){if(!current||!$('#console-body'))return;const p=current,entry=lastResults[p.id],r=entry?.result;$$('#console-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.console===consoleTab));
 if(consoleTab==='input'){$('#console-body').innerHTML=`<label class="muted" style="font-size:11px">标准输入 · 点击“运行”使用这组数据</label><textarea class="custom-input" id="custom-input" aria-label="自定义标准输入" spellcheck="false"></textarea><div class="empty-small">运行只显示结果，不计入题目完成度。文件题会使用第一个样例的测试文件。</div>`;$('#custom-input').value=state.drafts[p.id]?.input??p.tests[0].input;$('#custom-input').oninput=()=>{saveDraft();};return;}
 if(consoleTab==='diagnostics'){let d=r?.diagnostics||'尚无编译诊断。运行或检查代码后，编译错误和警告会显示在这里。';$('#console-body').innerHTML=`${analysisControls()}${entry?diagnosticCards(entry):''}<pre class="diagnostic">${esc(d).replace(/main\.c:(\d+):(\d+)/g,(_,l,c)=>`<button class="diagnostic-link" data-line="${l}" data-col="${c}">main.c:${l}:${c}</button>`)}</pre>`;$$('[data-line]').forEach(b=>b.onclick=()=>jumpTo(+b.dataset.line,+b.dataset.col));bindDiagnosticLinks();bindAnalysisControls();return;}
 if(busy&&busy.problemID===p.id){$('#console-body').innerHTML=`<div class="console-placeholder"><div class="check-icon loading-dot">◌</div><div><strong>正在编译并${busy.mode==='judge'?'验证检查点':'运行'}…</strong><p>使用本机 C17 编译器。每组输入独立执行。</p></div></div>`;return;}
 if(!r){$('#console-body').innerHTML=`${analysisControls()}<div class="console-placeholder"><div class="check-icon">✓</div><div><strong>写好了吗？让代码接受检验。</strong><p>点击“检查全部”，逐项验证基本样例和边界条件。</p></div></div><div class="checklist">${p.tests.map((t,i)=>`<span class="check-chip">${String(i+1).padStart(2,'0')} &nbsp; ${esc(t.name)}</span>`).join('')}</div>`;bindAnalysisControls();return;}
 const pass=r.checks.filter(c=>c.status==='passed').length,ok=r.status==='passed'||r.status==='ran';
 $('#console-body').innerHTML=`${analysisControls()}<div class="result-summary"><strong class="${ok?'pass':'error'}">${ok?'✓':'!'} ${statusLabels[r.status]??r.status}</strong><small>${entry.mode==='judge'?`${pass} / ${p.tests.length} 检查点`:'自定义运行'}${entry.code!==codeFor(p)?' · 代码已修改':''}</small></div>${subtaskResults(p,entry)}${diagnosticCards(entry)}${r.diagnostics?`<details ${r.checks.length?'':'open'}><summary class="muted" style="font-size:11px">编译器输出 · 点击“编译诊断”可定位行</summary><pre class="diagnostic">${esc(r.diagnostics)}</pre></details>`:''}${r.checks.map((c,i)=>`<details class="check-result" ${!['passed'].includes(c.status)?'open':''}><summary><span class="${['passed','ran'].includes(c.status)?'pass':'error'}">${['passed','ran'].includes(c.status)?'✓':'×'}</span>${esc(c.name)}<span class="${['passed','ran'].includes(c.status)?'pass':'error'}">${statusLabels[c.status]}</span><small>${c.milliseconds} ms</small></summary><div class="result-detail"><div><label>输入</label><pre>${esc(c.input||'（空）')}</pre></div><div><label>${entry.mode==='run'?'标准输出':'实际输出'}</label><pre>${esc(c.actual||'（空）')}</pre></div>${entry.mode==='judge'?`<div class="wide"><label>期望输出</label><pre>${esc(c.expected||'（空）')}</pre></div>`:''}${c.stderr||c.fileMessage?`<div class="wide"><label>诊断信息</label><pre class="error">${esc(c.stderr+'\n'+c.fileMessage)}</pre></div>`:''}</div></details>`).join('')}`;bindDiagnosticLinks();bindAnalysisControls();
}
function updateBusy(){if(!$('#run-button'))return;$('#run-button').disabled=!!busy;$('#judge-button').disabled=!!busy;$('#stop-button').hidden=!busy;$('#console-label').textContent=busy?'COMPILING / RUNNING':'LOCAL EXECUTION';}
function startRun(mode){if(!current||busy)return;saveDraft();flush();if(!native){toast('当前为浏览器界面预览，请打开 CPractice 桌面应用进行本地编译。');return;}busy={problemID:current.id,mode,assisted:!!state.assistedProblems?.[current.id]||revealed.has(current.id)};consoleTab='checks';updateBusy();renderConsole();post(mode,{mode,problemID:current.id,code:codeFor(current),input:state.drafts[current.id]?.input??current.tests[0].input,exercise:current.generated?{id:current.id,tests:current.tests}:undefined});}
function editorChanged(){if(!current)return;window.CEditor?.changed($('#code'));const code=$('#code').value;$('#highlight').innerHTML=highlight(code)+'\n';$('#line-numbers').textContent=Array.from({length:code.split('\n').length},(_,i)=>i+1).join('\n');syncScroll();cursorPosition();saveDraft();hideAnalysisHover();queueMicrotask(syncAnalysisAnnotations);if($('#pass-state'))$('#pass-state').textContent=state.progress[current.id]?.code===code?'✓ 当前代码已通过':completed(current.id)?'代码已修改 · 可重新验证':'编写你的解答';}
function syncScroll(){const e=$('#code');if(!e)return;$('#highlight').scrollTop=e.scrollTop;$('#highlight').scrollLeft=e.scrollLeft;$('#line-numbers').scrollTop=e.scrollTop;}
function cursorPosition(){const e=$('#code');if(!e)return;const before=e.value.slice(0,e.selectionStart),lines=before.split('\n');$('#cursor-position').textContent=`Ln ${lines.length}, Col ${lines.at(-1).length+1}`;}
function insert(text,start,end){const e=$('#code');e.focus();if(start!==undefined)e.setSelectionRange(start,end??start);document.execCommand('insertText',false,text);editorChanged();}
function bindEditor(){const e=$('#code');e.oninput=editorChanged;e.onscroll=syncScroll;e.onclick=cursorPosition;e.onkeyup=cursorPosition;
 e.onkeydown=ev=>{if(ev.isComposing)return;const s=e.selectionStart,t=e.selectionEnd,val=e.value;
 if(ev.key==='Tab'){ev.preventDefault();if(s!==t||ev.shiftKey){const a=val.lastIndexOf('\n',s-1)+1,b=t>s&&val[t-1]==='\n'?t-1:t,block=val.slice(a,b),text=block.split('\n').map(l=>ev.shiftKey?l.replace(/^ {1,4}/,''):'    '+l).join('\n');insert(text,a,b);e.setSelectionRange(a,a+text.length);}else insert('    ');return;}
 if(ev.key==='Enter'){ev.preventDefault();const line=val.slice(val.lastIndexOf('\n',s-1)+1,s),indent=line.match(/^\s*/)[0],extra=line.trimEnd().endsWith('{')?'    ':'';if(extra&&val[t]==='}'){insert('\n'+indent+extra+'\n'+indent);e.setSelectionRange(s+1+indent.length+4,s+1+indent.length+4);}else insert('\n'+indent+extra);return;}
 if((ev.metaKey||ev.ctrlKey)&&ev.key==='/'){ev.preventDefault();const a=val.lastIndexOf('\n',s-1)+1,b=val.indexOf('\n',t),end=b<0?val.length:b,lines=val.slice(a,end).split('\n'),uncomment=lines.every(l=>/^\s*\/\//.test(l));const text=lines.map(l=>uncomment?l.replace(/^(\s*)\/\/ ?/,'$1'):'// '+l).join('\n');insert(text,a,end);e.setSelectionRange(a,a+text.length);return;}
 if(!ev.metaKey&&!ev.ctrlKey&&!ev.altKey){const pairs={'(':')','[':']','{':'}','"':'"',"'":"'"};if(pairs[ev.key]){if((ev.key==='"'||ev.key==="'")&&val[s]===ev.key&&s===t){ev.preventDefault();e.setSelectionRange(s+1,s+1);return;}ev.preventDefault();insert(ev.key+val.slice(s,t)+pairs[ev.key]);e.setSelectionRange(s+1,t+1);return;}if(')]}'.includes(ev.key)&&val[s]===ev.key&&s===t){ev.preventDefault();e.setSelectionRange(s+1,s+1);return;}}
 };
 e.ondragover=ev=>{ev.preventDefault();};e.ondrop=async ev=>{ev.preventDefault();const f=ev.dataTransfer.files[0];if(!f||!f.name.toLowerCase().endsWith('.c'))return toast('请拖入 .c 源文件');if(f.size>262144)return toast('文件不能超过 256 KB');const target=current.id;try{const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(current?.id!==target)return;importCode(text,f.name);}catch{toast('无法读取文件，请使用 UTF-8 编码');}};
 editorChanged();
}
function importCode(code,name){if(!current)return;state.drafts[current.id]={...state.drafts[current.id],code,name};$('#code').value=code;$('#file-name').textContent=name;delete lastResults[current.id];editorChanged();renderConsole();toast(`已导入 ${name}，原文件不会被修改`);}
function applyFont(){const f=state.font??13;window.CEditor?.font(f);$$('#code,#highlight,#line-numbers').forEach(el=>el.style.fontSize=f+'px');}
function jumpTo(line,col=1){if(window.CEditor?.instance){window.CEditor.jump(line,col);return;}const e=$('#code'),lines=e.value.split('\n');const idx=lines.slice(0,line-1).reduce((a,l)=>a+l.length+1,0)+col-1;e.focus();e.setSelectionRange(idx,idx);e.scrollTop=Math.max(0,(line-4)*23);syncScroll();cursorPosition();}
function showFind(){if(window.CEditor?.instance){window.CEditor.find();return;}if(!$('#findbar'))return;$('#findbar').hidden=false;$('#find-input').focus();$('#find-input').select();}
function findNext(){const e=$('#code'),term=$('#find-input').value;if(!term)return;let i=e.value.indexOf(term,e.selectionEnd);if(i<0)i=e.value.indexOf(term);if(i<0)return toast('未找到匹配内容');e.focus();e.setSelectionRange(i,i+term.length);e.scrollTop=Math.max(0,(e.value.slice(0,i).split('\n').length-4)*23);syncScroll();cursorPosition();}
function renderHistory(){const list=[...state.history].reverse();$('#main').innerHTML=`<div class="page"><div class="eyebrow">YOUR PRACTICE JOURNAL</div><h1 class="page-title">每一次尝试，都有迹可循。</h1><p class="subtitle">保存最近 200 次完整验证的代码快照。运行自定义输入不会计入提交记录。</p><div class="section-head" style="margin-top:23px"><p>${list.length} 条本机记录</p><div><button class="button quiet small" id="backup-button">导出学习记录</button>${window.CPlatform?.desktop?'<button class="button quiet small" id="restore-backup-button">导入备份 / 跨系统迁移</button>':''}</div></div>${list.length?list.map((h,i)=>`<div class="history-card"><span class="${h.status==='passed'?'pass':'error'}">${h.status==='passed'?'✓':'○'}</span><div><strong>${h.problemID} · ${esc(byID(h.problemID)?.title??'练习')}</strong><p>${new Date(h.time).toLocaleString('zh-CN')} · ${statusLabels[h.status]??h.status} · ${h.passed}/${h.total} 检查点${h.score!=null?' · '+h.score+'/100 分':''}</p></div><button class="button quiet small" data-history="${i}">查看代码</button></div>`).join(''):'<div class="empty">完成第一次“检查全部”后，你的提交记录会出现在这里。</div>'}</div>`;if($('#restore-backup-button'))$('#restore-backup-button').onclick=()=>{flush();post('restoreBackup');};$('#backup-button').onclick=()=>{flush();post('backup');};$$('[data-history]').forEach(b=>b.onclick=()=>{const h=list[+b.dataset.history];showModal(`${h.problemID} · 提交快照`,`<p>${new Date(h.time).toLocaleString('zh-CN')} · ${statusLabels[h.status]}</p><pre class="codeblock" style="max-height:380px;overflow:auto">${highlight(h.code)}</pre><button id="restore-snapshot" class="button">恢复到编辑器</button>`,()=>{$('#restore-snapshot').onclick=()=>{saveDraft();state.drafts[h.problemID]={...state.drafts[h.problemID],code:h.code};state.assistedProblems??={};if(h.assisted)state.assistedProblems[h.problemID]=true;$('#modal').close();current=null;openProblem(h.problemID);toast('已恢复提交快照');};});});}
function showModal(title,body,after){$('#modal-body').innerHTML=`<h2>${esc(title)}</h2>${body}`;$('#modal').showModal();after?.();}
function showHelp(){showModal('欢迎来到 CPractice',`<p>一套本地编译、支持联网模型分析的 C 语言练习工作台。先从“初识 C”开始，每道题按 <b>读题 → 写代码 → 运行 → 检查全部 → 复盘</b> 的顺序完成。</p><h3>编辑器与扩展</h3><p>应用内使用 Monaco：自动缩进、颜色区分、折叠、多光标、查找替换、命令面板与代码片段。clangd 提供补全、悬浮、参数提示、当前文件定义/引用跳转与重命名；clang-format 负责格式化。语义服务需 Command Line Tools。Monaco 不承载 VS Code 扩展；工具栏“VS Code”会打开本机真实扩展工作区，取回代码后可在本应用验证。</p><h3>编辑器快捷键</h3>${[['⌘ ↵','运行自定义输入'],['⌘ ⇧ ↵','验证所有检查点'],['⌘ O / ⌘ S','导入 .c / 保存草稿'],['⌘ F / ⌘ /','查找 / 切换行注释'],['Tab / ⇧ Tab','缩进 / 取消缩进']].map(([k,v])=>`<div class="shortcut"><span>${v}</span><code>${k}</code></div>`).join('')}<h3>本地运行说明</h3><p>使用 Apple Clang（C17）编译，需已安装 Command Line Tools。每个测试在独立临时目录执行，限制 CPU 时间与输出大小，并用 macOS 进程沙盒禁止网络和个人目录访问。只运行你信任的源码；这不是虚拟机级隔离。</p><p>题目按输出行为验证；指针、递归等写法由知识卡与学习自检辅助掌握。有限测试不能证明所有输入都正确。</p><p>代码与进度保存到 ~/Library/Application Support/CPractice/state.json。提交记录页可导出备份。教程与编译练习无需联网；“详细分析”通过已登录的 Codex 联网调用 GPT-5.6-Sol Medium，发送本题题面、当前代码、最近一次不同代码、本次检查结果与教程引用。模型结果保存于本机，不自动修改代码。完成通知显示在底部并可关闭；悬浮玫红问题行可看具体分析，悬浮代码末尾蓝青色分析条可看复杂度与整体复盘。修改代码后，行标记以紫色保留并注明待复核，插入或删除代码后会重新定位；已删除的行不再标记。再次详细分析会更新颜色与分析内容。外部参考链接会在浏览器打开。</p>`);}
window.receiveNative=message=>{
 const {type,payload}=message;
 if(type==='runtimeStatus'){if($('#runtime-info'))$('#runtime-info').textContent=`系统：${payload.platform} / ${payload.architecture}\n编译器：${payload.compiler}\nclangd：${payload.clangd?'已安装':'未安装'} · 格式化：${payload.formatter?'已安装':'未安装'}\nCodex：${payload.codex?'已安装':'未安装'} · VS Code：${payload.vscode?'已安装':'未安装'}`;return;}
 if(receiveStudy(type,payload)||receiveRemedial(type,payload))return;
 if(['analysisStatus','analysisResult','analysisError'].includes(type)){receiveAnalysis(type,payload);return;}
 if(type==='language'){window.CEditor?.receive(payload);if(payload.serviceError)toast(payload.serviceError);return;}
 if(type==='state'){state={...state,...payload,drafts:payload.drafts??{},progress:payload.progress??{},favorites:payload.favorites??[],history:payload.history??[],reviews:payload.reviews??{}};loaded=true;initStudy();migrateLearning();render();CRemedial.restore();}
 else if(type==='saved'){$('#save-status').textContent='✓ 草稿与学习进度已保存';if($('#draft-dot'))$('#draft-dot').style.color='#80aa8b';}
 else if(type==='result'){if(payload.problemID.startsWith('L')){handleLessonResult(payload);return;}const runAssisted=!!busy?.assisted;busy=false;lastResults[payload.problemID]=payload;const r=payload.result;
  if(payload.mode==='judge'&&r.status!=='cancelled'){const assisted=runAssisted;recordLearning(payload.problemID,byID(payload.problemID).module,r.status==='passed',assisted,judgeRatio(byID(payload.problemID),r));state.history.push({assisted,score:byID(payload.problemID).subtasks?.length?scoreSubtasks(byID(payload.problemID),r).earned:undefined,problemID:payload.problemID,time:new Date().toISOString(),status:r.status,passed:r.checks.filter(c=>c.status==='passed').length,total:byID(payload.problemID).tests.length,code:payload.code});state.history=state.history.slice(-200);if(r.status==='passed')state.progress[payload.problemID]={passed:true,time:new Date().toISOString(),code:payload.code};persist();}
  updateSidebar();updateBusy();if(current?.id===payload.problemID){renderConsole();$('#pass-state').textContent=r.status==='passed'&&payload.code===codeFor(current)?'✓ 当前代码已通过':completed(current.id)?'✓ 曾通过全部检查':'继续完善你的解答';}else if(page==='tutorial')renderLessonResult();else if(page==='home')renderHome();else if(page==='complexity')renderComplexity();else if(page==='learning')renderLearning();else if(page==='mistakes')renderMistakes();else if(page==='history')renderHistory();toast(`${payload.problemID} · ${statusLabels[r.status]??r.status}`);
 }else if(type==='imported')importCode(payload.code,payload.name);else if(type==='notice'||type==='error')toast(payload);
};
$$('#primary-nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('#help-button').onclick=showHelp;$('#close-modal').onclick=()=>$('#modal').close();
document.addEventListener('keydown',ev=>{if(ev.isComposing)return;if(ev.key==='Escape'&&$('#findbar')&&!$('#findbar').hidden){$('#findbar').hidden=true;return;}if(!(ev.metaKey||ev.ctrlKey))return;if(current&&ev.key==='Enter'&&!ev.target.closest('.annotation-ask,.annotation-note')){ev.preventDefault();startRun(ev.shiftKey?'judge':'run');}if(current&&ev.key.toLowerCase()==='f'&&!window.CEditor?.instance){ev.preventDefault();showFind();}if(ev.key.toLowerCase()==='s'){ev.preventDefault();saveDraft();flush();toast('已保存当前草稿');}if(current&&ev.key.toLowerCase()==='o'){ev.preventDefault();post('import');}});
window.addEventListener('pagehide',flush);
if(native){post('ready');}else{try{state={...state,...JSON.parse(localStorage.getItem('cpractice-preview')||'{}')};}catch{}loaded=true;initStudy();migrateLearning();render();CRemedial.restore();}
window.CPracticeTest={notice:toast,openProblem,navigate,startRun,editorChanged,importCode,snapshot(){saveDraft();return state;},get state(){return state;},get busy(){return busy;},get results(){return lastResults;}};
