'use strict';
function complexityCard(p){const c=p.complexity;if(!c)return '';return `<section class="complexity-card"><div class="eyebrow">REASON ABOUT COST</div><h3>时间与空间，分别推导</h3><div class="complexity-pair"><div><small>时间复杂度</small><strong>${esc(c.time)}</strong></div><div><small>额外空间复杂度</small><strong>${esc(c.space)}</strong></div></div><p class="fulltext">${esc(c.reason)}</p>${c.alternative?`<h4>朴素方法与改进思路</h4><p class="fulltext">${esc(c.alternative)}</p>`:''}<p class="note">先明确输入规模，再数操作次数和同时存活的辅助内存。递归调用栈也算额外空间；输出空间是否计入需单独说明。</p><button class="button quiet small" data-complexity-lab>打开复杂度实验室 →</button></section>`;}
function complexityEstimate(n){return [{name:'O(1)',label:'直接访问一个元素',count:1},{name:'O(log n)',label:'每次把搜索范围减半',count:Math.ceil(Math.log2(n))},{name:'O(n)',label:'遍历一次',count:n},{name:'O(n log n)',label:'分层归并的比较量级',count:n*Math.ceil(Math.log2(n))},{name:'O(n²)',label:'所有有序数对',count:n*n},{name:'O(2ⁿ)',label:'枚举所有子集',count:Math.pow(2,n)}];}
function readableCount(n){return !Number.isFinite(n)?'超过数值显示范围':n>=1e12?n.toExponential(2):Math.round(n).toLocaleString('zh-CN');}
function renderComplexity(){
 $('#main').innerHTML=`<div class="page"><div class="eyebrow">ALGORITHM LAB</div><h1 class="page-title">输入变大时，算法会发生什么？</h1><p class="subtitle">复杂度描述增长趋势。它不是本机秒数，也不等同于代码行数。先定义输入规模 n，再分析工作量。</p><div class="insight-grid"><section class="insight-card"><h2>移动滑块，观察增长</h2><label>输入规模 n = <b id="complexity-n">32</b></label><input id="complexity-slider" type="range" min="1" max="10" value="5" aria-label="输入规模指数" style="width:100%;margin:20px 0;accent-color:var(--green)"><p class="note">取 n=2ᵏ，每移动一格规模翻倍。下面是代表性操作数，常数开销和硬件差异未计入；大O是上界表达。</p><div id="complexity-bars"></div></section><section class="insight-card"><h2>额外空间看“同时需要多少”</h2><div id="memory-examples"></div><p class="note">输入数组通常单独说明，不计入额外空间；若复制数组，副本要计入。若需要返回 n 个结果，输出空间 O(n) 必须明确。栈上一帧的实际字节数由编译器决定。</p><h3>递归次数 ≠ 栈空间</h3><p class="subtitle">二叉递归可能总共执行指数次调用，但若最大同时调用深度为 n，调用栈空间仍可能是 O(n)。反过来，递归二分的时间 O(log n)、栈空间 O(log n)，循环二分的额外空间可为 O(1)。</p></section></div><div class="insight-grid"><section class="insight-card"><h2>并列循环：相加</h2><pre class="codeblock">${highlight('for (int i = 0; i < n; ++i) {\n    sum += a[i];\n}\nfor (int i = 0; i < n; ++i) {\n    a[i] *= 2;\n}')}</pre><p class="subtitle">两段各执行 n 次，总量 2n，时间 O(n)。sum 和下标只占常数个变量，额外空间 O(1)。循环外已有输入数组不重复算作额外空间。</p></section><section class="insight-card"><h2>嵌套循环：按真实次数求和</h2><pre class="codeblock">${highlight('for (int i = 0; i < n; ++i) {\n    for (int j = i + 1; j < n; ++j) {\n        compare(a[i], a[j]);\n    }\n}')}</pre><p class="subtitle">内层次数随 i 变化： (n−1)+(n−2)+…+1 = n(n−1)/2，因此时间 O(n²)。只有两个下标仍是 O(1) 额外空间。双指针也可能用嵌套写法，但指针若总共只前进 n 次，时间可能为 O(n)。</p></section></div><section class="insight-card"><h2>解综合题时的五步自检</h2><ol><li><p>定义规模：n 是元素数，m 是边数或字符串长度？有多个独立规模就保留多个符号。</p></li><li><p>先写朴素解：枚举什么，最多多少次？可否复用已经算过的信息？</p></li><li><p>推导改进解：每个元素访问几次；排序成本是否也算上；DP的状态数乘以每个状态的转移成本。</p></li><li><p>清点额外内存：数组、哈希表、队列、递归栈、临时复制；说明是否包含输出。</p></li><li><p>明确口径：最坏、平均或均摊。动态数组追加通常均摊 O(1)，某一次扩容仍可能 O(n)。用输入上限检查设计是否合理。</p></li></ol><button class="button primary" id="complexity-practice">进入综合题练习 →</button> <button class="button quiet" id="complexity-tutorial">复习算法教程</button></section></div>`;
 const update=()=>{const n=2**Number($('#complexity-slider').value);$('#complexity-n').textContent=n;const estimates=complexityEstimate(n),logMax=Math.log10(n*n)+1;
 $('#complexity-bars').innerHTML=estimates.map(v=>`<div class="growth-row"><div><strong>${v.name}</strong><span>${v.label}</span><b>${Number.isFinite(v.count)?readableCount(v.count):'约 10^'+(n*Math.log10(2)).toFixed(1)}</b></div><i style="width:${Math.min(100,100*Math.log10(v.count+1)/logMax)}%"></i></div>`).join('')+'<p class="note">条形长度使用对数刻度并截顶；请比较右侧数值，而非把条长当作倍数。</p>';
 $('#memory-examples').innerHTML=`<table class="problem-table"><tbody><tr><td>一个计数器</td><td>O(1)</td><td>与 n 无关</td></tr><tr><td>保存 n 个 int 的副本</td><td>O(n)</td><td>假定 int 为 4 字节：${readableCount(n*4)} B</td></tr><tr><td>n × n 辅助矩阵</td><td>O(n²)</td><td>假定元素 4 字节：${readableCount(n*n*4)} B</td></tr><tr><td>深度 n 的递归</td><td>O(n)</td><td>最多 n 层同时存活</td></tr></tbody></table>`;};$('#complexity-slider').oninput=update;update();$('#complexity-practice').onclick=()=>navigate('comprehensive');$('#complexity-tutorial').onclick=()=>openTutorial(15);
}
