'use strict';
let coursebookID='P01',coursebookStage='prelude';
function openCoursebook(id){const lesson=window.C_COURSEBOOK.lessons.find(l=>l.id===id);if(!lesson)return;saveDraft();current=null;page='coursebook';coursebookID=id;coursebookStage=lesson.stage;render();}
function coursebookEntry(){return '<div class="coursebook-entry"><button class="button quiet" data-coursebook="P01">从零开始：环境与学习方法 →</button><button class="button quiet" data-coursebook="A01">算法与竞赛进阶 →</button><button class="button quiet" data-coursebook="G001">100 道竞赛题逐题导读 →</button></div>';}
function bindCoursebookEntries(host=document){host.querySelectorAll('[data-coursebook]').forEach(b=>b.onclick=()=>openCoursebook(b.dataset.coursebook));}
function courseFlowchart(kind){
 const labels=kind==='compile'?['源文件 .c','编译与链接','是否成功？','执行程序','读取诊断，修改源文件']:kind==='branch'?['输入余额、价格','读取两个数值','余额 ≥ 价格？','扣款并输出余额','输出“余额不足”']:['开始：sum=0，i=0','准备本场分数','i < 3？','sum += score[i]；i += 1','输出 sum，结束'];
 return `<figure class="course-flow" data-no-annotate><svg viewBox="0 0 760 430" role="img" aria-label="${esc(labels.join('；'))}"><defs><marker id="course-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="currentColor"/></marker></defs><g fill="none" stroke="currentColor" stroke-width="2"><rect x="245" y="12" width="270" height="48" rx="24"/><rect x="245" y="95" width="270" height="48"/><path d="M380 173 L515 223 L380 273 L245 223 Z"/><rect x="50" y="330" width="295" height="48"/><rect x="425" y="330" width="290" height="48"/><path marker-end="url(#course-arrow)" d="M380 60 V95 M380 143 V173 M245 223 H198 V330 M515 223 H570 V330"/>${kind==='loop'?'<path marker-end="url(#course-arrow)" d="M50 354 H22 V223 H245"/>':''}</g><g fill="currentColor" text-anchor="middle" font-size="16">${[[380,42,0],[380,125,1],[380,229,2],[198,360,3],[570,360,4]].map(([x,y,i])=>`<text x="${x}" y="${y}">${esc(labels[i])}</text>`).join('')}<text x="210" y="285">是</text><text x="550" y="285">否</text>${kind==='loop'?'<text x="90" y="205">下一轮</text>':''}</g></svg><figcaption>沿箭头手算一次，再把步骤翻译成代码。图形只表达控制流，不执行程序。</figcaption></figure>`;
}
function renderCoursebook(){
 const host=document.querySelector('#main'),book=window.C_COURSEBOOK,l=book.lessons.find(l=>l.id===coursebookID)||book.lessons[0],md=x=>CStudy.renderMarkdown(x||'');
 host.innerHTML=`<div class="tutorial-page"><div class="tutorial-heading"><div><div class="eyebrow">C PRACTICE / ${l.stage==='prelude'?'START HERE':'ALGORITHMS'}</div><h1>${l.stage==='prelude'?'开始编程之前':l.stage==='worked'?'100 道竞赛题逐题导读':'算法与竞赛课程'}</h1><p class="subtitle">先手算具体例子，再理解机制、前提与复杂度。</p></div></div>${coursebookEntry()}<div class="tutorial-layout"><aside class="lesson-outline"><label>查找课程<input id="coursebook-search" class="notes-input" placeholder="如：最短路、逆元、EOF" aria-label="查找进阶与前置课程"></label><div id="coursebook-outline">${book.lessons.filter(x=>x.stage===l.stage).map(x=>`<button class="lesson-link ${x.id===l.id?'active':''}" data-coursebook="${x.id}"><span>${esc(x.id)}</span><div>${esc(x.title)}</div></button>`).join('')}</div><button class="button quiet" id="coursebook-coverage">查看大纲与题库覆盖表</button><p class="muted">NOI 大纲：2025 修订版<br>核查日期 ${esc(book.checkedAt)}</p></aside><article class="lesson-article"><span class="id-cell">${esc(l.id)}</span><h2 class="tutorial-reading-heading">${esc(l.title)}</h2>${l.prerequisites.length?`<p>建议先学：${l.prerequisites.map(id=>`<button class="text-btn" data-coursebook="${esc(id)}">${esc(book.lessons.find(x=>x.id===id)?.title||id)}</button>`).join('、')}</p>`:''}<section class="explanation beginner"><div class="explanation-label">第一层 · 小白理解</div>${md(l.beginner)}</section><section class="explanation professional"><div class="explanation-label">第二层 · 专业理解</div>${md(l.professional)}</section><h3>用伪代码把逻辑连起来</h3><pre class="codeblock pseudocode">${esc(l.pseudocode)}</pre>${l.diagram?courseFlowchart(l.diagram):''}${l.id==='P05'?'<button class="button quiet" id="open-course-flow">在 VS Code 中编辑流程图（首次安装 draw.io）</button>':''}${l.code?`<h3>核心实现 · 逐行注释</h3><pre class="codeblock">${highlight(l.code)}</pre>`:''}<section class="term-bridge"><h3>生活说法与术语</h3><div class="table-scroll"><table><thead><tr><th>生活说法</th><th>术语</th><th>准确含义</th></tr></thead><tbody>${l.terms.map(t=>`<tr><td>${esc(t.plain)}</td><td>${esc(t.term)}</td><td>${esc(t.meaning)}</td></tr>`).join('')}</tbody></table></div><h3>最容易误解的地方</h3><ul>${l.pitfalls.map(s=>`<li><p>${esc(s)}</p></li>`).join('')}</ul></section>${l.complexity?`<section class="complexity-card"><h3>复杂度如何得到</h3>${md(l.complexity)}</section>`:''}<h3>理解检查 · 先回答，再展开</h3>${l.questions.map((q,i)=>`<section class="foundation-check"><h4>${i+1}. ${esc(q.question)}</h4><button class="button quiet small" data-course-answer="${i}">查看参考答案（小窗）</button></section>`).join('')}<h3>配套编程练习</h3><p>先读题、明确输入与边界；实现后运行检查点。先修知识不足时，返回上面的课程补齐。</p>${l.practice.map(id=>{const p=byID(id);return p?`<button class="reference-link" data-course-practice="${esc(id)}"><strong>${esc(id)} · ${esc(p.title)}</strong><small>${esc(p.topic||'基础实践')}</small></button>`:'';}).join('')}<div class="lesson-completion"><button class="button quiet" id="course-prev">← 上一课</button><button class="button primary" id="course-next">下一课 →</button></div></article></div></div>`;
 bindCoursebookEntries(host);const flowButton=host.querySelector('#open-course-flow');if(flowButton)flowButton.onclick=()=>post('openFlowchart',{});host.querySelectorAll('[data-course-answer]').forEach(b=>b.onclick=()=>{const q=l.questions[+b.dataset.courseAnswer];showModal('参考答案',`<h3>${esc(q.question)}</h3>${md(q.answer)}`);});host.querySelectorAll('[data-course-practice]').forEach(b=>b.onclick=()=>openProblem(b.dataset.coursePractice));
 const list=book.lessons.filter(x=>x.stage===l.stage),i=list.indexOf(l);host.querySelector('#course-prev').disabled=i===0;host.querySelector('#course-next').disabled=i===list.length-1;host.querySelector('#course-prev').onclick=()=>openCoursebook(list[i-1].id);host.querySelector('#course-next').onclick=()=>openCoursebook(list[i+1].id);
 host.querySelector('#coursebook-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();host.querySelectorAll('#coursebook-outline button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q));};
 host.querySelector('#coursebook-coverage').onclick=()=>showModal('大纲与题库课程索引',`<p>以官方2025版大纲为核对依据。覆盖表示有学习入口，不代表仅阅读即达到竞赛熟练程度。C++专属内容需要独立的C++编译环境。</p><div class="table-scroll"><table><thead><tr><th>范围</th><th>知识点</th><th>学习入口</th></tr></thead><tbody>${book.coverage.map(c=>`<tr><td>${esc(c.scope)}</td><td>${esc(c.topic)}</td><td>${esc(c.lessons.join('、'))}</td></tr>`).join('')}</tbody></table></div>`);
 window.CWorkspace?.readingControls(host);window.CAnnotations?.mount(host.querySelector('.lesson-article'),{docID:`coursebook:${l.id}`,context:`${l.title}\n${l.beginner}\n${l.professional}`});host.scrollTop=0;
}
