'use strict';
// The tutor transports only explicit study content through the native bridge.
const studyRequests=new Map();
let studyArchiveID=null,studyQuote='',studyImages=[],studyDraft='',studyStatus='',studyUploading=false,studyUploadToken=0,archiveSelection=new Set(),codexInfo=null;
function initStudy(){state.studyArchives??=[];state.annotations??=[];state.remedialExercises??=[];state.remedialJobs??=[];for(const a of state.studyArchives)if(a.pending){a.pending=false;a.error='上次回答中断，问题已保留，可重试。';}for(const j of state.remedialJobs)if(j.status==='running'){j.status='error';j.error='上次生成中断，请重试。';}}
function renderStudyMarkdown(text){
 const maths=[];const source=String(text??'').replace(/```[\s\S]*?```|`[^`\n]*`|\$\$([\s\S]+?)\$\$|\\\[([\s\S]+?)\\\]|\\\(([\s\S]+?)\\\)|(?<!\\)\$([^$\n]+?)\$/g,(all,a,b,c,d)=>{if(all.startsWith('`'))return all;const i=maths.push({text:a??b??c??d,display:!!(a??b)})-1;return `CPMATHPLACEHOLDER${i}END`;});
 const box=document.createElement('div');box.innerHTML=DOMPurify.sanitize(marked.parse(source,{breaks:false}),{USE_PROFILES:{html:true},FORBID_TAGS:['img','style','input','button','form','iframe','video','audio'],FORBID_ATTR:['style','id'],ALLOW_DATA_ATTR:false});
 const walker=document.createTreeWalker(box,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 for(const node of nodes){if(!node.textContent.includes('CPMATHPLACEHOLDER'))continue;const frag=document.createDocumentFragment();let last=0;for(const m of node.textContent.matchAll(/CPMATHPLACEHOLDER(\d+)END/g)){frag.append(node.textContent.slice(last,m.index));const math=maths[+m[1]],span=document.createElement('span');if(math)katex.render(math.text,span,{displayMode:math.display,throwOnError:false,trust:false,strict:'warn',maxExpand:500,maxSize:20});frag.append(span);last=m.index+m[0].length;}frag.append(node.textContent.slice(last));node.replaceWith(frag);}
 box.querySelectorAll('details').forEach(d=>d.removeAttribute('open'));
 box.querySelectorAll('pre code').forEach(c=>{if(!c.className||/language-(c|cpp|c17)/.test(c.className))c.innerHTML=highlight(c.textContent);});
 box.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href')??'';if(!/^https:\/\//i.test(href))a.removeAttribute('href');else{a.dataset.external=href;a.removeAttribute('href');a.setAttribute('role','link');a.tabIndex=0;}});
 return box.innerHTML;
}
function studyBindings(root){root.querySelectorAll('[data-external]').forEach(a=>{a.onclick=()=>post('openURL',{url:a.dataset.external});a.onkeydown=e=>{if(e.key==='Enter')a.click();};});}
function askStudy(messages,extra={}){return new Promise((resolve,reject)=>{
 if(!native){reject(Error('请在 Mac 应用中使用模型问答，并在“连接 Codex”页登录。'));return;}
 if(studyRequests.size){reject(Error('上一条问答仍在生成，请完成或取消后再提问。'));return;}
 const requestID=crypto.randomUUID();studyRequests.set(requestID,{resolve,reject,...extra});post('studyAsk',{requestID,messages,context:extra.context??'',quote:extra.quote??''});
});}
function askSelection(options){return askStudy([{role:'user',content:options.question}],{context:options.context,quote:options.quote,annotationID:options.annotationID}).then(r=>r.answer);}
function studyArchive(){return state.studyArchives?.find(a=>a.id===studyArchiveID);}
function rememberComposer(){const input=$('#study-input');if(input){studyDraft=input.value;const a=studyArchive();if(a){a.draft=studyDraft;a.quote=studyQuote;persist();}}}
function openStudyArchive(id){studyUploadToken++;rememberComposer();studyArchiveID=id;const a=studyArchive();studyDraft=a?.draft??'';studyQuote=a?.quote??'';studyImages=[];renderStudy();}
function newStudy(){studyUploadToken++;rememberComposer();studyArchiveID=null;studyDraft='';studyQuote='';studyImages=[];if(page!=='agent')navigate('agent');studyDraft='';studyQuote='';renderStudy();}
function chatHTML(a){return `<div class="study-conversation" aria-label="C语言问答对话"><div class="study-chat-head"><div><span class="eyebrow">GPT-5.6-SOL · HIGH</span><h2>${esc(a?.title??'一起把 C 语言学明白')}</h2></div>${page==='archives'?'<button class="icon-btn" id="close-archive" aria-label="关闭存档小窗">×</button>':'<button class="button quiet small" id="new-study">新对话 ＋</button>'}</div>${a?.summary?`<details class="study-summary"><summary>本次知识整理</summary><div class="markdown">${renderStudyMarkdown(a.summary)}</div></details>`:''}<div class="study-messages" id="study-messages">${a?.messages.length?a.messages.map((m,i)=>`<section class="study-message ${m.role}" data-message="${i}"><div class="message-role">${m.role==='user'?'你':'C 语言导师 · High'}</div>${m.quote?`<blockquote class="study-quote">“${esc(m.quote)}”</blockquote>`:''}${m.images?.length?`<div class="study-photo-row">${m.images.map(im=>`<img src="${esc(im.dataURL)}" alt="${esc(im.name)}">`).join('')}</div>`:''}<div class="markdown study-answer" data-answer="${i}">${renderStudyMarkdown(m.content)}</div></section>`).join(''):'<div class="study-welcome"><span class="study-orb">C</span><h3>一处不明白，就从这里问起。</h3><p>输入代码、文字或拖入题目照片。回答包含小白例子、专业机制、常见误解与理解检查。</p><p>支持 Markdown、LaTeX（如 $O(n)$）和 C 代码块。</p></div>'}${a?.pending?`<div class="study-thinking" role="status">${esc(studyStatus||'正在整理问题并生成双层讲解…')} <button class="button quiet small" id="cancel-study">取消</button></div>`:''}${a?.error?`<div class="study-error">${esc(a.error)} <button class="button small" id="retry-study">重试上条问题</button></div>`:''}</div><div class="study-composer">${studyQuote?`<div class="study-quote"><button class="icon-btn" id="clear-study-quote" aria-label="移除引用">×</button>“${esc(studyQuote)}”</div>`:''}<div id="study-upload" class="study-drop" role="button" tabindex="0" aria-label="点击或拖入题目照片">＋ 点击选择照片，或拖到这里 <span>PNG / JPEG / WebP · 最多 4 张，每张 8 MB</span><input id="study-file" type="file" accept="image/png,image/jpeg,image/webp" multiple hidden></div><div id="study-attachments"></div><textarea id="study-input" aria-label="输入C语言问题" placeholder="粘贴你的 C 代码，或说说哪里不理解…\n用三个反引号包裹代码，可保留格式。" spellcheck="false">${esc(studyDraft)}</textarea><details class="study-preview"><summary>预览 Markdown / 公式</summary><div class="markdown" id="study-preview-body"></div></details><div class="study-send-row"><small>发送对话文字和最近8张照片至已登录 Codex；完整内容保存在本机。</small><button class="button primary" id="study-send" ${a?.pending||studyUploading?'disabled':''}>发送 ↑</button></div></div></div>`;}
function renderStudy(){
 const a=studyArchive();if(page==='archives')renderArchives(a);else $('#main').innerHTML=`<div class="study-page">${chatHTML(a)}</div>`;
 bindChat(a);studyBindings($('#main'));
}
function bindChat(a){
 if(!$('#study-input'))return;
 $('#study-input').oninput=e=>{studyDraft=e.target.value;if(a){a.draft=studyDraft;persist();}$('#study-preview-body').innerHTML=renderStudyMarkdown(studyDraft);studyBindings($('#study-preview-body'));};
 $('#study-input').onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();sendStudy();}};
 $('#study-send').onclick=()=>sendStudy();if($('#new-study'))$('#new-study').onclick=newStudy;
 if($('#close-archive'))$('#close-archive').onclick=()=>{rememberComposer();studyArchiveID=null;renderStudy();};
 if($('#clear-study-quote'))$('#clear-study-quote').onclick=()=>{rememberComposer();studyQuote='';if(a)a.quote='';renderStudy();};
 if($('#cancel-study'))$('#cancel-study').onclick=()=>post('cancelStudy');
 if($('#retry-study'))$('#retry-study').onclick=()=>sendStudy(true);
 const drop=$('#study-upload'),file=$('#study-file');drop.onclick=e=>{if(e.target!==file)file.click();};drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();file.click();}};file.onchange=()=>addStudyFiles(file.files);
 drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');addStudyFiles(e.dataTransfer.files);};
 renderAttachments();
 if(a)$('#study-messages').querySelectorAll('.study-answer').forEach(root=>{const i=+root.dataset.answer;CAnnotations.mount(root,{docID:`archive:${a.id}:${i}`,context:'C语言问答：'+a.title,onAsk:({quote,question})=>{studyArchiveID=a.id;studyQuote=quote;studyDraft=question;renderStudy();sendStudy();return '已在当前存档继续提问。';}});});
}
async function addStudyFiles(files){
 if(studyUploading)return toast('正在处理照片，请稍等后再添加。');studyUploading=true;const token=studyUploadToken;if($('#study-send'))$('#study-send').disabled=true;const dest=studyArchiveID;const added=[];for(const f of Array.from(files??[])){
 if(studyImages.length+added.length>=4){toast('每轮最多上传4张照片。');break;}
 if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8*1024*1024){toast('照片需为 PNG / JPEG / WebP 且不超过8MB。');continue;}
 try{const image=await createImageBitmap(f);if(image.width*image.height>40_000_000){image.close();throw Error();}const scale=Math.min(1,2400/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);image.close();added.push({name:f.name,dataURL:canvas.toDataURL('image/jpeg',.92)});}catch{toast('这张图片无法读取，请换一张清晰照片。');}
 }
 studyUploading=false;if($('#study-send'))$('#study-send').disabled=!!studyArchive()?.pending;if(dest!==studyArchiveID||token!==studyUploadToken)return;studyImages.push(...added.slice(0,4-studyImages.length));renderAttachments();
}
function renderAttachments(){const box=$('#study-attachments');if(!box)return;box.innerHTML=studyImages.map((im,i)=>`<div class="study-thumb"><img src="${esc(im.dataURL)}" alt="${esc(im.name)}"><button data-remove-photo="${i}" aria-label="移除 ${esc(im.name)}">×</button></div>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{studyImages.splice(+b.dataset.removePhoto,1);renderAttachments();});}
async function sendStudy(retry=false){
 retry=retry===true;
 if(studyUploading)return toast('照片仍在处理，请完成后再发送。');
 rememberComposer();let a=studyArchive();if(a?.pending||studyRequests.size)return toast('请等当前回答完成，或取消后再提问。');
 if(!retry&&!studyDraft.trim()&&!studyImages.length)return toast('请输入问题或选择照片。');
 if(!native)return toast('请在 Mac 应用中使用问答。');
 if(a?.messages.length>=60&&!retry)return toast('当前对话已达到30轮，请新建对话继续。');
 if(!a){a={id:crypto.randomUUID(),title:'新的 C 语言问题',summary:'',messages:[],createdAt:new Date().toISOString(),pinned:false};state.studyArchives.unshift(a);studyArchiveID=a.id;}
 if(!retry){a.messages.push({role:'user',content:studyDraft.trim()||'请解释照片中的C语言题目；看不清的内容请先指出。',quote:studyQuote,images:studyImages.slice()});studyDraft='';studyQuote='';studyImages=[];a.draft='';a.quote='';}
 a.error='';a.pending=true;persist();renderStudy();$('#study-messages')?.scrollTo(0,$('#study-messages').scrollHeight);
 try{let remaining=8;const messages=a.messages.slice().reverse().map(m=>{const images=remaining?(m.images??[]).slice(-remaining):[];remaining-=images.length;return {role:m.role,content:(m.quote?'引用内容：\n“'+m.quote+'”\n\n':'')+m.content+((m.images?.length??0)>images.length?'\n[较早照片本轮未附，请依据既有文字转写；缺少信息时请要求重新附图。]':''),images};}).reverse();const reply=await askStudy(messages,{archiveID:a.id});a.messages.push({role:'assistant',content:reply.answer,time:reply.time});a.title=reply.title;a.summary=reply.summary;a.updatedAt=reply.time??new Date().toISOString();a.pending=false;persist();flush();if(['agent','archives'].includes(page)&&studyArchiveID===a.id){renderStudy();$('#study-messages')?.scrollTo(0,$('#study-messages').scrollHeight);}else toast('C语言导师已回答，内容已保存在存档。');}
 catch(e){a.pending=false;a.error=e.message;persist();if(['agent','archives'].includes(page)&&studyArchiveID===a.id)renderStudy();else toast('问答未完成：'+e.message);}
}
function renderArchives(a){
 const list=[...(state.studyArchives??[])].sort((x,y)=>Number(y.pinned)-Number(x.pinned)||String(y.updatedAt??y.createdAt).localeCompare(String(x.updatedAt??x.createdAt)));
 $('#main').innerHTML=`<div class="archive-page ${a?'archive-open':''}"><section class="archive-index"><div class="eyebrow">YOUR KNOWLEDGE ARCHIVE</div><h1>存档</h1><p>完整保留每轮问答、引用与照片；选中回答还能批注和继续提问。</p><div class="archive-actions"><button class="button small" id="select-archives">${list.length&&archiveSelection.size===list.length?'取消全选':'全选'}</button><button class="button small" id="pin-archives">置顶所选</button><button class="button small" id="unpin-archives">取消置顶</button><button class="button quiet small" id="delete-archives">删除所选</button></div><span class="muted">已选 ${archiveSelection.size} 项</span><div class="archive-list">${list.map(x=>`<article class="archive-card ${x.pinned?'pinned':''} ${a?.id===x.id?'active':''}"><input type="checkbox" aria-label="选择 ${esc(x.title)}" data-select-archive="${x.id}" ${archiveSelection.has(x.id)?'checked':''}><button class="archive-link" data-archive="${x.id}"><small>${x.pinned?'◆ 已置顶 · ':''}${new Date(x.updatedAt??x.createdAt).toLocaleDateString('zh-CN')}</small><strong>${esc(x.title)}</strong><p>${esc(x.summary||x.messages[0]?.content||'尚未回答')}</p><span>${x.messages.filter(m=>m.role==='assistant').length} 轮回答</span></button></article>`).join('')||'<div class="empty">还没有存档。导师回答后，会自动整理并保存在这里。</div>'}</div></section>${a?chatHTML(a):''}</div>`;
 $$('[data-archive]').forEach(b=>b.onclick=()=>openStudyArchive(b.dataset.archive));$$('[data-select-archive]').forEach(b=>b.onchange=()=>{rememberComposer();b.checked?archiveSelection.add(b.dataset.selectArchive):archiveSelection.delete(b.dataset.selectArchive);renderStudy();});
 $('#select-archives').onclick=()=>{rememberComposer();archiveSelection=archiveSelection.size===list.length?new Set():new Set(list.map(x=>x.id));renderStudy();};
 const pin=value=>{if(!archiveSelection.size)return toast('先选择存档。');rememberComposer();state.studyArchives.forEach(x=>{if(archiveSelection.has(x.id))x.pinned=value;});persist();renderStudy();};$('#pin-archives').onclick=()=>pin(true);$('#unpin-archives').onclick=()=>pin(false);
 $('#delete-archives').onclick=()=>{if(!archiveSelection.size)return toast('先选择存档。');if(state.studyArchives.some(x=>archiveSelection.has(x.id)&&x.pending))return toast('所选存档仍在回答，请先取消或等待完成。');showModal('删除所选存档',`<p>将删除 ${archiveSelection.size} 项问答存档及其批注。删除后无法恢复。</p><button class="button" id="confirm-archive-delete">确认删除</button>`,()=>{$('#confirm-archive-delete').onclick=()=>{state.studyArchives=state.studyArchives.filter(x=>!archiveSelection.has(x.id));state.annotations=state.annotations.filter(x=>![...archiveSelection].some(id=>x.docID?.startsWith('archive:'+id+':')));if(archiveSelection.has(studyArchiveID))studyArchiveID=null;archiveSelection.clear();persist();flush();$('#modal').close();renderStudy();};});};
}
function receiveStudy(type,payload){
 if(type.startsWith('codex')){codexInfo=payload;if(page==='connection')renderConnection();return true;}
 if(!type.startsWith('study'))return false;
 const entry=studyRequests.get(payload.requestID);if(!entry)return true;
 if(type==='studyStatus'){studyStatus=payload.message;const e=$('.study-thinking');if(e)e.firstChild.textContent=studyStatus+' ';return true;}
 studyRequests.delete(payload.requestID);studyStatus='';if(type==='studyResult')entry.resolve(payload);else entry.reject(Error(payload.message||'问答未完成，请重试。'));return true;
}
function renderConnection(){
 $('#main').innerHTML=`<div class="page connection-page"><div class="eyebrow">LOCAL CODEX CONNECTION</div><h1>连接本机 Codex</h1>${window.CPlatform?.desktop?'<button class="button" id="runtime-check">检测编译与编辑环境</button><pre id="runtime-info" class="note"></pre>':''}<p class="subtitle">使用你在本机的 Codex 登录。应用不要求粘贴账号密码或 API 密钥。</p><div class="connection-status"><h3>${esc(codexInfo?.message??'点击检测，确认本机是否已安装并登录。')}</h3>${codexInfo?.url?`<button class="button" id="login-url">打开官方登录页面 ↗</button>`:''}${codexInfo?.code?`<p>一次性设备码：<code>${esc(codexInfo.code)}</code></p>`:''}<button class="button primary" id="check-codex">检测连接</button> <button class="button" id="login-codex">使用 ChatGPT 登录</button> <button class="button quiet" id="cancel-login">取消登录</button></div><ol class="connection-steps"><li><h3>安装 Codex</h3><p>已有桌面版或 CLI 可先检测。还没安装时，打开官方安装指南，按当前系统步骤安装，三个系统均可使用 npm install -g @openai/codex。</p><button class="text-btn" data-doc="https://developers.openai.com/codex/cli/">Codex 官方安装指南 ↗</button></li><li><h3>用已有 ChatGPT 账号登录</h3><p>点击上方登录，在官方网页由你完成认证。已有套餐是否包含 Codex、可用模型和剩余额度，以账户权限为准。API 密钥模式另行计费。</p><p>若设备登录不可用，可在终端运行 <code>codex login</code> 完成浏览器登录，再回到这里检测。</p></li><li><h3>开始学习</h3><p>代码详细分析使用 GPT-5.6-Sol / Medium；教程提问与 C 语言导师使用 GPT-5.6-Sol / High。模型不可用或额度不足时会明确报错，不会偷偷换模型。</p></li></ol><div class="lesson-banner"><h3>发送和保存哪些内容</h3><p>问答只发送你选择的教程文字、对话、代码与照片；错误定向出题发送本题题面和本次错误。模型回答、批注和学习记录保存在本机，可用“使用指南”备份。联网问答会使用你的 Codex 额度。</p><button class="text-btn" data-doc="https://developers.openai.com/codex/auth/">认证与套餐使用方式 · 官方说明 ↗</button></div></div>`;
 if($('#runtime-check'))$('#runtime-check').onclick=()=>post('runtimeStatus');
 $('#check-codex').onclick=()=>post('codexStatus');$('#login-codex').onclick=()=>post('codexLogin');$('#cancel-login').onclick=()=>post('cancelCodexLogin');$$('[data-doc]').forEach(b=>b.onclick=()=>post('openURL',{url:b.dataset.doc}));if($('#login-url'))$('#login-url').onclick=()=>post('openURL',{url:codexInfo.url});
}
function renderAcknowledgements(){const data=window.C_ACKNOWLEDGEMENTS;$('#main').innerHTML='<div class="page"><div class="eyebrow">SOURCES & THANKS</div><h1>来源与致谢</h1><div id="acknowledgements-body" class="markdown"></div></div>';const box=$('#acknowledgements-body');if(!data){box.textContent='来源清单正在加载。';return;}const render=value=>{if(Array.isArray(value))return value.map(render).join('');if(value&&typeof value==='object'){const title=value.title??value.name??value.category;return `<section class="ack-card">${title?`<h3>${esc(title)}</h3>`:''}${Object.entries(value).filter(([k])=>!['title','name','category','id'].includes(k)).map(([k,v])=>typeof v==='object'?render(v):/^https:\/\//.test(String(v))?`<p><button class="text-btn" data-external="${esc(v)}">${esc(v)} ↗</button></p>`:`<p>${esc(v)}</p>`).join('')}</section>`;}return `<p>${esc(value)}</p>`;};box.innerHTML=render(data);studyBindings(box);}
window.CStudy={init:initStudy,render:renderStudy,receive:receiveStudy,askSelection,renderMarkdown:renderStudyMarkdown,bindMarkdown:studyBindings,ask:askStudy,addFiles:addStudyFiles,newConversation:newStudy,openArchive:openStudyArchive,get requests(){return studyRequests;}};
