'use strict';
// Explicit --smoke-test uses disposable app data and never calls a model.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
async function run({window,store,dataDir,restoreState,quit}){
 const checks=[];
 try{
  await window.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(window.CPracticeTest&&(document.querySelector('.module-card')||document.querySelector('#learning-profile'))){clearInterval(t);resolve(true);}else if(++n>100){clearInterval(t);reject(Error('home not loaded'));}},100);})`);
  const onboarding=await window.webContents.executeJavaScript(`(()=>{const form=document.querySelector('#learning-profile');if(!form)throw Error('new profile must show questionnaire');for(const [name,value] of [['experience','new'],['goal','basics'],['pace','guided']])form.querySelector('[name="'+name+'"][value="'+value+'"]').checked=true;form.requestSubmit();const a={level:CPracticeTest.snapshot().learningProfile.level,collapsedCatalog:!document.querySelector('.home-catalog').open,hiddenCompetition:document.querySelector('[data-page="olympiad"]').hidden};document.querySelector('#more-features').click();a.allFeatures=!document.querySelector('[data-page="olympiad"]').hidden;document.querySelector('#sidebar-resize').dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));a.maxWidth=CPracticeTest.snapshot().workspaceLayout.sidebarWidth;document.querySelector('#sidebar-resize').dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));a.collapsed=document.body.classList.contains('sidebar-collapsed');document.querySelector('#sidebar-toggle').click();a.restored=!document.body.classList.contains('sidebar-collapsed');return a;})()`);
  assert.equal(onboarding.level,'starter');assert.equal(onboarding.collapsedCatalog,true);assert.equal(onboarding.hiddenCompetition,true);assert.equal(onboarding.allFeatures,true);assert.equal(onboarding.maxWidth,360);assert.equal(onboarding.collapsed,true);assert.equal(onboarding.restored,true);checks.push(onboarding);
  const data=await window.webContents.executeJavaScript(`(()=>{const a={bridge:!!window.webkit?.messageHandlers?.native,nodeHidden:typeof require==='undefined',cards:document.querySelectorAll('.module-card').length};document.querySelector('#chapters button[data-module="6"]').click();a.fullTutorial=!!document.querySelector('[data-annotation-root],.lesson-content,.lesson-article')||document.body.innerText.includes('完整课程目录');a.points=document.body.innerText.includes('EOF');CPracticeTest.openProblem('C001');a.editor=!!document.querySelector('.monaco-editor');CPracticeTest.navigate('agent');a.tutor=!!document.querySelector('#study-send');a.math=CStudy.renderMarkdown('\\\\(x^2\\\\)').includes('katex');a.sanitized=!CStudy.renderMarkdown('<img src=x onerror="alert(1)"><script>alert(1)</script>').includes('onerror');return a;})()`);
  assert.equal(data.bridge,true);assert.equal(data.nodeHidden,true);assert.equal(data.cards,15);assert.equal(data.fullTutorial,true);assert.equal(data.points,true);assert.equal(data.editor,true);assert.equal(data.tutor,true);assert.equal(data.math,true);assert.equal(data.sanitized,true);checks.push(data);
  const course=await window.webContents.executeJavaScript(`(()=>{CPracticeTest.navigate('home');document.querySelector('[data-coursebook="P01"]').click();const a={entry:document.body.innerText.includes('电脑怎样执行'),articles:document.querySelectorAll('.lesson-article').length};openCoursebook('P05');a.diagram=!!document.querySelector('.course-flow svg');a.drawio=!!document.querySelector('#open-course-flow');openCoursebook('A13');a.dp=document.body.innerText.includes('容量倒序');a.hiddenAnswers=!document.querySelector('.modal-backdrop');openCoursebook('G100');a.practice=!!document.querySelector('[data-course-practice="H100"]');CPracticeTutorialTest.openTutorial(1);CPracticeTutorialTest.tutorialSelect(0,'F01-10');a.noDuplicateExample=!document.body.innerText.includes('看一个具体例子');return a;})()`);
  assert.equal(course.entry,true);assert.equal(course.articles,1);assert.equal(course.diagram,true);assert.equal(course.drawio,true);assert.equal(course.dp,true);assert.equal(course.practice,true);assert.equal(course.noDuplicateExample,true);checks.push(course);

  const navigation=await window.webContents.executeJavaScript(`(()=>{CPracticeTutorialTest.openTutorial(1,CURRICULUM.tutorials[0].lessons.length-1);document.querySelector('#next-lesson').click();const a={foundation:document.querySelector('.lesson-article').innerText.includes('FOUNDATION'),noTrace:!document.body.innerText.includes('把过程慢放一遍')};const id=CPracticeTest.snapshot().lessonLast.foundationID;CPracticeTest.navigate('home');CPracticeTest.navigate('tutorial');a.resumeFoundation=CPracticeTest.snapshot().lessonLast.foundationID===id;document.querySelector('[data-reading-fullscreen]').click();a.fullscreen=document.body.classList.contains('reading-fullscreen');document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));a.exitFullscreen=!document.body.classList.contains('reading-fullscreen');document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',altKey:true,shiftKey:true,bubbles:true}));a.nextChapter=CPracticeTest.snapshot().lessonLast.module===2;document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',altKey:true,bubbles:true}));a.nextLesson=CPracticeTest.snapshot().lessonLast.index===1;const input=document.createElement('input');document.body.append(input);input.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',altKey:true,bubbles:true}));a.inputIgnored=CPracticeTest.snapshot().lessonLast.index===1;input.remove();return a;})()`);
  for(const [key,value] of Object.entries(navigation))assert.equal(value,true,key);checks.push(navigation);
  await window.webContents.executeJavaScript(`(()=>{CPracticeTest.openProblem('C001');CEditor.instance.setValue(CURRICULUM.problems.find(p=>p.id==='C001').solution);CPracticeTest.startRun('judge');})()`);
  const judged=await window.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{const r=CPracticeTest.results.C001;if(r){clearInterval(t);resolve(r.result);}else if(++n>400){clearInterval(t);reject(Error('judge timeout'));}},100);})`);
  assert.equal(judged.status,'passed',JSON.stringify(judged));checks.push({nativeIPCJudge:'passed'});
  await window.webContents.executeJavaScript(`window.webkit.messageHandlers.native.postMessage({action:'save',state:CPracticeTest.snapshot()})`);
  for(let n=0;(await store.load()).history?.length!==1;n++){if(n>100)throw Error('submission was not saved');await new Promise(resolve=>setTimeout(resolve,25));}
  await restoreState({drafts:{},progress:{},favorites:[],history:[],reviews:{},last:'C001'});
  const restored=await window.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(window.CPracticeTest&&(document.querySelector('.module-card')||document.querySelector('#learning-profile'))){clearInterval(t);resolve(CPracticeTest.snapshot().history.length);}else if(++n>100){clearInterval(t);reject(Error('restored home not loaded'));}},100);})`);
  assert.equal(restored,0,'The old document must not overwrite an imported backup');
  await store.queue;
  assert.equal((await store.load()).history.length,0);
  const backup=(await fs.readdir(dataDir)).find(n=>n.startsWith('before-restore-'));
  assert.ok(backup);assert.equal(JSON.parse(await fs.readFile(path.join(dataDir,backup),'utf8')).history.length,1);
  checks.push({backupRestore:'passed',previousRecordsBackedUp:true});
  const dest=process.env.CPRACTICE_SMOKE_REPORT||path.join(process.cwd(),'tests/reports/desktop-smoke.json');await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,JSON.stringify({platform:process.platform,arch:process.arch,passed:true,checks},null,2));console.log('Desktop smoke passed:',process.platform,process.arch);
 }finally{await quit();}
}
module.exports={run};
